runtime: nodejs20
service: frontend-056
instance_class: F1

handlers:
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

  - url: /
    static_files: build/index.html
    upload: build/index.html
